version: "3.7"

networks:
  nginx_network:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${NGINX_OUT}:80
    volumes:
      - .:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_network

  php:
    container_name: nullpointer_php
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - nginx_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    networks:
      - nginx_network

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: npointer
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - ./database:/data/postgres
    networks:
      - nginx_network
