# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        main_config:
            extraPlugins: "templates"
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', '-', 'Link', '-', 'NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image',  '-', '-', 'TextColor', 'BGColor'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []        